---
  - name: "Instalar java e unzip"
    apt:
      update_cache: yes
      cache_valid_time: 3600
      name: ["openjdk-11-jre", "unzip"]
      state: latest
    become: yes
  
  - name: "Copiar aplicação"
    copy:
      src: "files/springapp.zip"
      dest: "/home/azureuser/springapp.zip"
    become: yes

  - name: "Desempacotar aplicação"
    unarchive:
      src: /home/azureuser/springapp.zip
      dest: /srv
      remote_src: yes
    become: yes

  - name: "Criar pasta logs springapp"
    file:
      path: /var/log/springapp
      state: directory
    become: yes

  - name: "Copiar serviço spring"
    copy:
      src: "files/springapp.service"
      dest: "/etc/systemd/system/springapp.service"
    become: yes

  - name: "Iniciar serviço"
    shell: "systemctl start springapp.service"
    become: yes

  - name: "Habilitar serviço"
    shell: "systemctl enable springapp.service"
    become: yes